server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.0.197
    #hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #server:
    #enableSelfPreservation: false
    #evictionIntervalTimerInMs: 4000
    #renewalPercentThreshold: 0.49